# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/MuratArs1an
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Step 3. Running GitHub Actions
Once you've added the code above and committed it, head to your Actions tab. Under "Workflows", you should see the "Generate Snake" Action you created above.

Workflow

Click "Run Workflow" and watch your workflow run. You can even expand your workflow and see what's happening in real time.

Running Actions

Once your workflow has finished running, you should have received a green âœ… "build" checkmark. If so, this means your Action is working nicely. If not, you'll have to go through the code and see where the errors are. The "build" status should give you some indication of where your errors lie. You can also compare it with the yaml file on my GitHub Profile README.

Build green

If you have the green "build" âœ… then you should be good to go. Head back to your repo's "Code" directory, and change your branch to "output". Here you'll find the two versions of your contribution graph with the snake eating it: a *.gif and a *.svg. The good thing about these files is the file is rewritten over itself every time the Action runs. Thus, your contribution graph will always be up to date.

CodeOutput

Step 4. Adding a contribution-eating snake to your profile
Now the final set is to add this to your profile. Grab the file location of your *.gif. It should be something like:

https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif

Add this to your profile by copying the file location onto a new line in your markdown file:

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif)

Now you should have a really cool looking snake eating your contributions!

GIFSnakeEating
Hopefully this guide was helpful for you and gives you a good base to start building and adding more Actions on your profile. What have you been adding to your GitHub Profile README? Other there other cool Actions I should be looking at?

Git Good (10 Part Series)
1
Using the GitHub CLI to update your repo
2
How to create and pin a gist on GitHub
...
6 more parts...
9
How to create a Profile README for your Organisation
10
How to automatically close your issues once you merge a PR
Top comments (33)

Subscribe
pic
Add to the discussion
 
 
kushaltanna24 profile image
KushalTanna24
â€¢
3 Haz 22

Work fine.! Here is mine - KushalTanna24


2
Like
 
 
msoftware profile image
Michael jentsch
â€¢
9 Tem 21

Great tutorial! Works for me.
Here's mine - github.com/msoftware


2
Like
 
 
gustavohgmartins profile image
Gustavo Martins
â€¢
3 Eyl 21

Awsome! How did you change the background-color?


Like
 
 
mishmanners profile image
Michelle Mannering
â€¢
3 Eyl 21

I didn't change the background colour. It's a .png/.svg image, meaning the background is transparent. It looks dark on mine because I have dark mode enabled on GitHub. You can enable it by clicking Settings --> Appearance --> choosing your mode.


1
Like
Thread
 
gustavohgmartins profile image
Gustavo Martins
â€¢
3 Eyl 21

Thank you! actually I was using the .gif version, so I switched to the .svg one and voilÃ¡


2
Like
Thread
 
mishmanners profile image
Michelle Mannering
â€¢
3 Eyl 21

Awesome! Glad to be of help ğŸ˜„


1
Like
 
 
l3on06 profile image
L3on06
â€¢
17 Åub

Hello everyone, before proceeding, please navigate to 'Settings -> Actions -> General -> Workflow Permissions' in your README.md file and select 'Read and Write' permissions. This is important because if you have other permissions selected, it may result in errors.


1
Like
 
 
jakon62508112 profile image
Jakob
â€¢
20 Oca â€¢ Edited

Getting this error when I try to run workflow and after it fails:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.


1
Like
 
 
shuvajitgeek profile image
Shuvajit
â€¢
1 Åub

go to setting -> action -> and check the workflow as read and write
(run build again) hopefully you will not get error


Like
 
 
hoangtien_2k3 profile image
HoÃ ng Anh Tiáº¿n
â€¢
29 Oca â€¢ Edited

It does not work for me. Can someone help me?
github.com/hoangtien2k3qx1

Error:
actions/checkout@v2, platane/snk@master, ad-m/github-push-action@master, and crazy-max/ghaction-github-pages@v2.1.3 are not allowed to be used in hoangtien2k3qx1/hoangtien2k3qx1. Actions in this workflow must be: within a repository owned by hoangtien2k3qx1.


1
Like
 
 
bpolaswar profile image
Bhumesh Polaswar
â€¢
17 Eki 21

Great worked for me. See github.com/bpolaswar
Thanks.


2
Like
 
 
wkylin profile image
wkylin.w
â€¢
1 May 22

Here's mine:
github.com/wkylin


1
Like
 
 
hudsonpufferfish profile image
Hudson Nguyen
â€¢
8 Oca

I got error "The process '/usr/bin/git' failed with exit code 128". Even though I tried to generate a new personal access token, it didn't work. Anybody has any solution for this error?


1
Like
 
 
nirav97120 profile image
Nirav Prajapati
â€¢
16 Ara 22

Awesome My github profile


1
Like
 
 
phuocantd profile image
An Nguyá»…n PhÆ°á»›c
â€¢
1 Haz 22

How to auto build workflow everyday


1
Like
 
 
laurasiiia profile image
Laura
â€¢
3 Oca 22 â€¢ Edited

Hi, i did everything right and even got the "build" status. But no output branch was created... why is that? Can someone help me? github.com/laurasiiia


1
Like
 
 
mishmanners profile image
Michelle Mannering
â€¢
4 Oca 22

I assume you're working off this folder: github.com/laurasiiia/laurasiiia/b...

Since you've got a newer repo (mine account was set up a number of years ago), you have the default branch set to "main". You might need to change the code to be "main" instead of "master".

I created a PR for you: github.com/laurasiiia/laurasiiia/p...
(run it and see if that works)... it might not but worth a shot. Feel free to jump in other people ğŸ˜„


1
Like
 
 
adityamangal1 profile image
Aditya Mangal
â€¢
22 Tem 21

Awesome Tutorial! ğŸ


1
Like
 
 
viveeeeeek profile image
VivekS.
â€¢
2 Eki 21

Awesome!


1
Like
 
 
zieldecastro profile image
Josiel de Castro Goudinho
â€¢
15 Eyl 21 â€¢ Edited

It does not work for me. Can someone help me?
github.com/zieldecastro
instagram.com/zieldecastro/


1
Like
 
 
shasank27 profile image
Shasank Periwal
â€¢
8 AÄŸu 21 â€¢ Edited

Great tutorial!
But can anyone help me, its not showing all my contributions
github.com/shasank27/shasank27


1
Like
 
 
mishmanners profile image
Michelle Mannering
â€¢
6 Eyl 21 â€¢ Edited

Hey Shasank. I can't see it on your profile, but to show all contributions, you need to make sure all contributions are turned on your profile. You can do this in your settings:

github.com/YOUR_PROFILE --> Settings --> Profile

Then scroll down to "Contributions" and check the box that says "Include private contributions on my profile".

Hope that helps.


1
Like
View full discussion (33 comments)
Code of Conduct â€¢ Report abuse
profile
Xata
PROMOTED

ğŸ“¢ Xata Content Hackathon (Aug 28 - Sep 30, 2023)
Xata cover image

To celebrate end-of-summer, Xata is sponsoring a content hackathon. Multiple prizes will be awarded including

ğŸ’° $500!!!
ğŸ Xata swag packs
ğŸ’°ğŸ ENTER TO WIN! ğŸğŸ’°

Read next
jobenjada profile image
ğŸ“ƒ ğŸ‘€ Run in-app surveys in your web app in 10 minutes with Formbricks ğŸ¤“â¤ï¸â€ğŸ”¥
Johannes - Aug 28

ashokan profile image
Pushing application metrics to otel-collector
Ashok Nagaraj - Aug 17

094459 profile image
AWS open source newsletter, #170
Ricardo Sueiras - Aug 21

hamed_farag profile image
Frontend Architecture: The Architecture (Part. 1)
Hamed Farag - Aug 17


Michelle Mannering
Follow
Developer Advocate | Hackathon Queen | International Speaker
LOCATION
Australia
EDUCATION
The University of Melbourne
WORK
Developer Advocate at GitHub
JOINED
29 May 2020
More from Michelle Mannering
How to get more suggestions from GitHub Copilot
#ai #tutorial #githubcopilot #github
Prompt engineering for AI: what is prompt engineering and how to get good results from AI engines
#ai #machinelearning #tutorial #beginners
Want to speak at a conference? Top tips for getting a CFP accepted
#career #tutorial #github #writing
DEV Community

Your Ad Here
your-ad-here

Explore DEV Advertising Options to start the conversation.


# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets
